name: "Kubernetes Action"
description: "Interacts with kubernetes clusters calling helm commands. Integrates support for AWS EKS."
branding:
  icon: 'anchor'
  color: 'blue'
inputs:
  args:
    description: "Arguments of helm"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.args }}
